trigger:
- main

parameters:
- name: package_version
  displayName: Package Version
  type: string
  default: 1.1

variables:
- name: PACKAGE_VERSION
  value: ${{ parameters.package_version }}.$(Build.BuildId)
- name: vmImageName
  value: 'ubuntu-22.04'

stages:
- stage: Build
  displayName: Build Package
  jobs:
      - job:
        displayName: ${{ variables.vmImageName }}
        pool:
          vmImage: $(vmImageName)
        strategy:
          matrix:
            Python310:
              python.version: '3.10'              
              env_file: 'environment_py310.yml'
              env_prereqs: 'python=3.10 numpy=1.22.4'
              
        steps:
        - bash: echo "##vso[task.prependpath]$CONDA/bin"
          displayName: Add conda to PATH
      
        - bash: |
            conda create -n build_env $(env_prereqs)
            conda activate build_env
          displayName: Create build environment
     
        - task: PipAuthenticate@1
          displayName: 'Pip Authenticate'
          inputs:
            artifactFeeds: 'Warn-on-Forecast/wofs-post'

        - bash: |
            source activate build_env
            python setup.py bdist_wheel
          displayName: Build wheel

        - script: 'pip install twine keyring artifacts-keyring'
          displayName: Install publishing prerequisites
  
        - task: TwineAuthenticate@1
          inputs:
            artifactFeed: 'Warn-on-Forecast/wofs-post'
          displayName: Authenticate Twine

        - script: |
            python -m twine upload -r wofs-post --config-file $(PYPIRC_PATH) --skip-existing dist/*.whl
          displayName: Publish Package

        - task: GithubRelease@1 
          displayName: 'Create GitHub Release'
          inputs:
            gitHubConnection: WarnOnForecast-Github
            repositoryName: NOAA-National-Severe-Storms-Laboratory/frdd-wofs-phi
            isPreRelease: false
            tagSource: userSpecifiedTag
            assets: dist/*.whl
            tag: $(PACKAGE_VERSION)-py$(python.version)
